version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "[%(asctime)s] %(name)34s %(levelprefix)s %(message)s"
  access:
    "()": uvicorn.logging.AccessFormatter
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "[%(asctime)s] %(name)34s %(levelprefix)s %(message)s"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
